/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package STRATEGO;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author esteb
 */
public class MiPerfil extends javax.swing.JFrame {

    private Player jugadorActual;
    private GameLog[] logsPartidos;
    FondoPanel fondo = new FondoPanel("/imagenes/background.jpeg");
    
    public MiPerfil(Player jugadorActual) {
        this.setContentPane(fondo);
        this.jugadorActual = jugadorActual;
        this.logsPartidos = LogManager.getLogsDelJugador(jugadorActual.getUsername());
        initComponents();
        setupUI();
        setLocationRelativeTo(null);
        actualizarDatosJugador();
        cargarLogsPartidos();
    }
    
    private void setupUI() {
        jPanel1.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        lblPuntos.setForeground(Color.WHITE);
        lblTotalJugadas.setForeground(Color.WHITE);
        lblHeroe.setForeground(Color.WHITE);
        lblVillano.setForeground(Color.WHITE);
        lblGanadas.setForeground(Color.WHITE);
        lblPerdidas.setForeground(Color.WHITE);
        textAreaLogs.setOpaque(false);
        textAreaLogs.setEditable(false);
        textAreaLogs.setFont(new Font("Arial", Font.PLAIN, 14));
        textAreaLogs.setForeground(Color.WHITE);
        textAreaLogs.setBackground(new Color(0, 0, 0, 100));
        
        // Configurar scroll pane
        jScrollPane1.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(Color.WHITE, 2), 
            "Historial de Partidos", 
            0, 0, 
            new Font("Arial", Font.BOLD, 14), 
            Color.WHITE
        ));
    }
    
    private void actualizarDatosJugador() {
        lblJugador.setText("Jugador: " + jugadorActual.getUsername());
        lblPuntos.setText("Puntos: " + jugadorActual.getPuntos());
        lblGanadas.setText("Partidos Ganados: " + jugadorActual.getGanadas());
        lblPerdidas.setText("Partidos Perdidos: " + jugadorActual.getPerdidas());
        lblTotalJugadas.setText("Total Partidos: " + jugadorActual.getTotalPartidas());
        lblHeroe.setText("Veces como Héroe: " + jugadorActual.getVecesHeroe());
        lblVillano.setText("Veces como Villano: " + jugadorActual.getVecesVillano());
    }
    
    private void cargarLogsPartidos() {
        StringBuilder textoLogs = new StringBuilder();
        
        if (logsPartidos.length == 0) {
            textoLogs.append("No hay partidos jugados aún.\n");
        } else {
            textoLogs.append("Últimos partidos (del más reciente al más antiguo):\n\n");
            
            for (int i = logsPartidos.length - 1; i >= 0; i--) {
                String logFormateado = logsPartidos[i].formatearLog(jugadorActual.getUsername());
                textoLogs.append("• ").append(logFormateado).append("\n");
            }
        }
        
        textAreaLogs.setText(textoLogs.toString());
        textAreaLogs.setCaretPosition(0); // Ir al inicio del texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        btnBorrarCuenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnCambiarPassword = new javax.swing.JButton();
        lblJugador = new javax.swing.JLabel();
        lblVillano = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblGanadas = new javax.swing.JLabel();
        lblHeroe = new javax.swing.JLabel();
        lblPerdidas = new javax.swing.JLabel();
        lblTotalJugadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaLogs = new javax.swing.JTextArea();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBorrarCuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBorrarCuenta.setText("Borrar Cuenta");

        btnVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCambiarPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCambiarPassword.setText("Cambiar Contraseña");
        btnCambiarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPasswordActionPerformed(evt);
            }
        });

        lblJugador.setBackground(new java.awt.Color(255, 255, 255));
        lblJugador.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblVillano.setBackground(new java.awt.Color(255, 255, 255));
        lblVillano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblPuntos.setBackground(new java.awt.Color(255, 255, 255));
        lblPuntos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPuntos.setToolTipText("");

        lblGanadas.setBackground(new java.awt.Color(255, 255, 255));
        lblGanadas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblHeroe.setBackground(new java.awt.Color(255, 255, 255));
        lblHeroe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHeroe.setToolTipText("");

        lblPerdidas.setBackground(new java.awt.Color(255, 255, 255));
        lblPerdidas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblTotalJugadas.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalJugadas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        textAreaLogs.setColumns(20);
        textAreaLogs.setRows(5);
        jScrollPane1.setViewportView(textAreaLogs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblGanadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(lblHeroe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPuntos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalJugadas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCambiarPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCambiarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnBorrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJugador)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntos)
                            .addComponent(lblTotalJugadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeroe)
                            .addComponent(lblVillano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGanadas)
                            .addComponent(lblPerdidas))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuJuego menujuego = new MenuJuego(jugadorActual);
        menujuego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCambiarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPasswordActionPerformed
        CambiarPassword cambiar = new CambiarPassword(jugadorActual);
        cambiar.setVisible(true);
        cambiar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCambiarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarCuenta;
    private javax.swing.JButton btnCambiarPassword;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGanadas;
    private javax.swing.JLabel lblHeroe;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblPerdidas;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblTotalJugadas;
    private javax.swing.JLabel lblVillano;
    private javax.swing.JTextArea textAreaLogs;
    // End of variables declaration//GEN-END:variables
}
