/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package STRATEGO;

/**
 *
 * @author esteb
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casilla1 = new javax.swing.JButton();
        casilla2 = new javax.swing.JButton();
        casilla3 = new javax.swing.JButton();
        casilla4 = new javax.swing.JButton();
        casilla5 = new javax.swing.JButton();
        casilla6 = new javax.swing.JButton();
        casilla7 = new javax.swing.JButton();
        casilla8 = new javax.swing.JButton();
        casilla9 = new javax.swing.JButton();
        casilla10 = new javax.swing.JButton();
        casilla11 = new javax.swing.JButton();
        casilla12 = new javax.swing.JButton();
        casilla13 = new javax.swing.JButton();
        casilla14 = new javax.swing.JButton();
        casilla15 = new javax.swing.JButton();
        casilla16 = new javax.swing.JButton();
        casilla17 = new javax.swing.JButton();
        casilla18 = new javax.swing.JButton();
        casilla19 = new javax.swing.JButton();
        casilla20 = new javax.swing.JButton();
        casilla21 = new javax.swing.JButton();
        casilla22 = new javax.swing.JButton();
        casilla23 = new javax.swing.JButton();
        casilla24 = new javax.swing.JButton();
        casilla25 = new javax.swing.JButton();
        casilla26 = new javax.swing.JButton();
        casilla27 = new javax.swing.JButton();
        casilla28 = new javax.swing.JButton();
        casilla29 = new javax.swing.JButton();
        casilla30 = new javax.swing.JButton();
        casilla31 = new javax.swing.JButton();
        casilla32 = new javax.swing.JButton();
        casilla33 = new javax.swing.JButton();
        casilla34 = new javax.swing.JButton();
        casilla35 = new javax.swing.JButton();
        casilla36 = new javax.swing.JButton();
        casilla37 = new javax.swing.JButton();
        casilla38 = new javax.swing.JButton();
        casilla39 = new javax.swing.JButton();
        casilla40 = new javax.swing.JButton();
        casilla41 = new javax.swing.JButton();
        casilla42 = new javax.swing.JButton();
        casilla43 = new javax.swing.JButton();
        casilla44 = new javax.swing.JButton();
        casilla45 = new javax.swing.JButton();
        casilla46 = new javax.swing.JButton();
        casilla47 = new javax.swing.JButton();
        casilla48 = new javax.swing.JButton();
        casilla49 = new javax.swing.JButton();
        casilla50 = new javax.swing.JButton();
        casilla51 = new javax.swing.JButton();
        casilla52 = new javax.swing.JButton();
        casilla53 = new javax.swing.JButton();
        casilla54 = new javax.swing.JButton();
        casilla55 = new javax.swing.JButton();
        casilla56 = new javax.swing.JButton();
        casilla57 = new javax.swing.JButton();
        casilla58 = new javax.swing.JButton();
        casilla59 = new javax.swing.JButton();
        casilla60 = new javax.swing.JButton();
        casilla61 = new javax.swing.JButton();
        casilla62 = new javax.swing.JButton();
        casilla63 = new javax.swing.JButton();
        casilla64 = new javax.swing.JButton();
        casilla65 = new javax.swing.JButton();
        casilla66 = new javax.swing.JButton();
        casilla67 = new javax.swing.JButton();
        casilla68 = new javax.swing.JButton();
        casilla69 = new javax.swing.JButton();
        casilla70 = new javax.swing.JButton();
        casilla71 = new javax.swing.JButton();
        casilla72 = new javax.swing.JButton();
        casilla73 = new javax.swing.JButton();
        casilla74 = new javax.swing.JButton();
        casilla75 = new javax.swing.JButton();
        casilla76 = new javax.swing.JButton();
        casilla77 = new javax.swing.JButton();
        casilla78 = new javax.swing.JButton();
        casilla79 = new javax.swing.JButton();
        casilla80 = new javax.swing.JButton();
        casilla81 = new javax.swing.JButton();
        casilla82 = new javax.swing.JButton();
        casilla83 = new javax.swing.JButton();
        casilla84 = new javax.swing.JButton();
        casilla85 = new javax.swing.JButton();
        casilla86 = new javax.swing.JButton();
        casilla87 = new javax.swing.JButton();
        casilla88 = new javax.swing.JButton();
        casilla89 = new javax.swing.JButton();
        casilla90 = new javax.swing.JButton();
        casilla91 = new javax.swing.JButton();
        casilla92 = new javax.swing.JButton();
        casilla93 = new javax.swing.JButton();
        casilla94 = new javax.swing.JButton();
        casilla95 = new javax.swing.JButton();
        casilla96 = new javax.swing.JButton();
        casilla97 = new javax.swing.JButton();
        casilla98 = new javax.swing.JButton();
        casilla99 = new javax.swing.JButton();
        casilla100 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        casilla1.setBackground(new java.awt.Color(204, 204, 204));
        casilla1.setForeground(new java.awt.Color(153, 153, 153));

        casilla2.setBackground(new java.awt.Color(204, 204, 204));
        casilla2.setForeground(new java.awt.Color(153, 153, 153));

        casilla3.setBackground(new java.awt.Color(204, 204, 204));
        casilla3.setForeground(new java.awt.Color(153, 153, 153));

        casilla4.setBackground(new java.awt.Color(204, 204, 204));
        casilla4.setForeground(new java.awt.Color(153, 153, 153));

        casilla5.setBackground(new java.awt.Color(204, 204, 204));
        casilla5.setForeground(new java.awt.Color(153, 153, 153));

        casilla6.setBackground(new java.awt.Color(204, 204, 204));
        casilla6.setForeground(new java.awt.Color(153, 153, 153));

        casilla7.setBackground(new java.awt.Color(204, 204, 204));
        casilla7.setForeground(new java.awt.Color(153, 153, 153));

        casilla8.setBackground(new java.awt.Color(204, 204, 204));
        casilla8.setForeground(new java.awt.Color(153, 153, 153));

        casilla9.setBackground(new java.awt.Color(204, 204, 204));
        casilla9.setForeground(new java.awt.Color(153, 153, 153));

        casilla10.setBackground(new java.awt.Color(204, 204, 204));
        casilla10.setForeground(new java.awt.Color(153, 153, 153));

        casilla11.setBackground(new java.awt.Color(204, 204, 204));
        casilla11.setForeground(new java.awt.Color(153, 153, 153));

        casilla12.setBackground(new java.awt.Color(204, 204, 204));
        casilla12.setForeground(new java.awt.Color(153, 153, 153));

        casilla13.setBackground(new java.awt.Color(204, 204, 204));
        casilla13.setForeground(new java.awt.Color(153, 153, 153));

        casilla14.setBackground(new java.awt.Color(204, 204, 204));
        casilla14.setForeground(new java.awt.Color(153, 153, 153));

        casilla15.setBackground(new java.awt.Color(204, 204, 204));
        casilla15.setForeground(new java.awt.Color(153, 153, 153));

        casilla16.setBackground(new java.awt.Color(204, 204, 204));
        casilla16.setForeground(new java.awt.Color(153, 153, 153));

        casilla17.setBackground(new java.awt.Color(204, 204, 204));
        casilla17.setForeground(new java.awt.Color(153, 153, 153));

        casilla18.setBackground(new java.awt.Color(204, 204, 204));
        casilla18.setForeground(new java.awt.Color(153, 153, 153));

        casilla19.setBackground(new java.awt.Color(204, 204, 204));
        casilla19.setForeground(new java.awt.Color(153, 153, 153));

        casilla20.setBackground(new java.awt.Color(204, 204, 204));
        casilla20.setForeground(new java.awt.Color(153, 153, 153));

        casilla21.setBackground(new java.awt.Color(204, 204, 204));
        casilla21.setForeground(new java.awt.Color(153, 153, 153));

        casilla22.setBackground(new java.awt.Color(204, 204, 204));
        casilla22.setForeground(new java.awt.Color(153, 153, 153));

        casilla23.setBackground(new java.awt.Color(204, 204, 204));
        casilla23.setForeground(new java.awt.Color(153, 153, 153));

        casilla24.setBackground(new java.awt.Color(204, 204, 204));
        casilla24.setForeground(new java.awt.Color(153, 153, 153));

        casilla25.setBackground(new java.awt.Color(204, 204, 204));
        casilla25.setForeground(new java.awt.Color(153, 153, 153));

        casilla26.setBackground(new java.awt.Color(204, 204, 204));
        casilla26.setForeground(new java.awt.Color(153, 153, 153));

        casilla27.setBackground(new java.awt.Color(204, 204, 204));
        casilla27.setForeground(new java.awt.Color(153, 153, 153));

        casilla28.setBackground(new java.awt.Color(204, 204, 204));
        casilla28.setForeground(new java.awt.Color(153, 153, 153));

        casilla29.setBackground(new java.awt.Color(204, 204, 204));
        casilla29.setForeground(new java.awt.Color(153, 153, 153));

        casilla30.setBackground(new java.awt.Color(204, 204, 204));
        casilla30.setForeground(new java.awt.Color(153, 153, 153));

        casilla31.setBackground(new java.awt.Color(204, 204, 204));
        casilla31.setForeground(new java.awt.Color(153, 153, 153));

        casilla32.setBackground(new java.awt.Color(204, 204, 204));
        casilla32.setForeground(new java.awt.Color(153, 153, 153));

        casilla33.setBackground(new java.awt.Color(204, 204, 204));
        casilla33.setForeground(new java.awt.Color(153, 153, 153));

        casilla34.setBackground(new java.awt.Color(204, 204, 204));
        casilla34.setForeground(new java.awt.Color(153, 153, 153));

        casilla35.setBackground(new java.awt.Color(204, 204, 204));
        casilla35.setForeground(new java.awt.Color(153, 153, 153));

        casilla36.setBackground(new java.awt.Color(204, 204, 204));
        casilla36.setForeground(new java.awt.Color(153, 153, 153));

        casilla37.setBackground(new java.awt.Color(204, 204, 204));
        casilla37.setForeground(new java.awt.Color(153, 153, 153));

        casilla38.setBackground(new java.awt.Color(204, 204, 204));
        casilla38.setForeground(new java.awt.Color(153, 153, 153));

        casilla39.setBackground(new java.awt.Color(204, 204, 204));
        casilla39.setForeground(new java.awt.Color(153, 153, 153));

        casilla40.setBackground(new java.awt.Color(204, 204, 204));
        casilla40.setForeground(new java.awt.Color(153, 153, 153));

        casilla41.setBackground(new java.awt.Color(204, 204, 204));
        casilla41.setForeground(new java.awt.Color(153, 153, 153));

        casilla42.setBackground(new java.awt.Color(204, 204, 204));
        casilla42.setForeground(new java.awt.Color(153, 153, 153));

        casilla43.setBackground(new java.awt.Color(204, 204, 204));
        casilla43.setForeground(new java.awt.Color(153, 153, 153));

        casilla44.setBackground(new java.awt.Color(204, 204, 204));
        casilla44.setForeground(new java.awt.Color(153, 153, 153));

        casilla45.setBackground(new java.awt.Color(204, 204, 204));
        casilla45.setForeground(new java.awt.Color(153, 153, 153));

        casilla46.setBackground(new java.awt.Color(204, 204, 204));
        casilla46.setForeground(new java.awt.Color(153, 153, 153));

        casilla47.setBackground(new java.awt.Color(204, 204, 204));
        casilla47.setForeground(new java.awt.Color(153, 153, 153));

        casilla48.setBackground(new java.awt.Color(204, 204, 204));
        casilla48.setForeground(new java.awt.Color(153, 153, 153));

        casilla49.setBackground(new java.awt.Color(204, 204, 204));
        casilla49.setForeground(new java.awt.Color(153, 153, 153));

        casilla50.setBackground(new java.awt.Color(204, 204, 204));
        casilla50.setForeground(new java.awt.Color(153, 153, 153));

        casilla51.setBackground(new java.awt.Color(204, 204, 204));
        casilla51.setForeground(new java.awt.Color(153, 153, 153));

        casilla52.setBackground(new java.awt.Color(204, 204, 204));
        casilla52.setForeground(new java.awt.Color(153, 153, 153));

        casilla53.setBackground(new java.awt.Color(204, 204, 204));
        casilla53.setForeground(new java.awt.Color(153, 153, 153));

        casilla54.setBackground(new java.awt.Color(204, 204, 204));
        casilla54.setForeground(new java.awt.Color(153, 153, 153));

        casilla55.setBackground(new java.awt.Color(204, 204, 204));
        casilla55.setForeground(new java.awt.Color(153, 153, 153));

        casilla56.setBackground(new java.awt.Color(204, 204, 204));
        casilla56.setForeground(new java.awt.Color(153, 153, 153));

        casilla57.setBackground(new java.awt.Color(204, 204, 204));
        casilla57.setForeground(new java.awt.Color(153, 153, 153));

        casilla58.setBackground(new java.awt.Color(204, 204, 204));
        casilla58.setForeground(new java.awt.Color(153, 153, 153));

        casilla59.setBackground(new java.awt.Color(204, 204, 204));
        casilla59.setForeground(new java.awt.Color(153, 153, 153));

        casilla60.setBackground(new java.awt.Color(204, 204, 204));
        casilla60.setForeground(new java.awt.Color(153, 153, 153));

        casilla61.setBackground(new java.awt.Color(204, 204, 204));
        casilla61.setForeground(new java.awt.Color(153, 153, 153));

        casilla62.setBackground(new java.awt.Color(204, 204, 204));
        casilla62.setForeground(new java.awt.Color(153, 153, 153));

        casilla63.setBackground(new java.awt.Color(204, 204, 204));
        casilla63.setForeground(new java.awt.Color(153, 153, 153));

        casilla64.setBackground(new java.awt.Color(204, 204, 204));
        casilla64.setForeground(new java.awt.Color(153, 153, 153));

        casilla65.setBackground(new java.awt.Color(204, 204, 204));
        casilla65.setForeground(new java.awt.Color(153, 153, 153));

        casilla66.setBackground(new java.awt.Color(204, 204, 204));
        casilla66.setForeground(new java.awt.Color(153, 153, 153));

        casilla67.setBackground(new java.awt.Color(204, 204, 204));
        casilla67.setForeground(new java.awt.Color(153, 153, 153));

        casilla68.setBackground(new java.awt.Color(204, 204, 204));
        casilla68.setForeground(new java.awt.Color(153, 153, 153));

        casilla69.setBackground(new java.awt.Color(204, 204, 204));
        casilla69.setForeground(new java.awt.Color(153, 153, 153));

        casilla70.setBackground(new java.awt.Color(204, 204, 204));
        casilla70.setForeground(new java.awt.Color(153, 153, 153));

        casilla71.setBackground(new java.awt.Color(204, 204, 204));
        casilla71.setForeground(new java.awt.Color(153, 153, 153));

        casilla72.setBackground(new java.awt.Color(204, 204, 204));
        casilla72.setForeground(new java.awt.Color(153, 153, 153));

        casilla73.setBackground(new java.awt.Color(204, 204, 204));
        casilla73.setForeground(new java.awt.Color(153, 153, 153));

        casilla74.setBackground(new java.awt.Color(204, 204, 204));
        casilla74.setForeground(new java.awt.Color(153, 153, 153));

        casilla75.setBackground(new java.awt.Color(204, 204, 204));
        casilla75.setForeground(new java.awt.Color(153, 153, 153));

        casilla76.setBackground(new java.awt.Color(204, 204, 204));
        casilla76.setForeground(new java.awt.Color(153, 153, 153));

        casilla77.setBackground(new java.awt.Color(204, 204, 204));
        casilla77.setForeground(new java.awt.Color(153, 153, 153));

        casilla78.setBackground(new java.awt.Color(204, 204, 204));
        casilla78.setForeground(new java.awt.Color(153, 153, 153));

        casilla79.setBackground(new java.awt.Color(204, 204, 204));
        casilla79.setForeground(new java.awt.Color(153, 153, 153));

        casilla80.setBackground(new java.awt.Color(204, 204, 204));
        casilla80.setForeground(new java.awt.Color(153, 153, 153));

        casilla81.setBackground(new java.awt.Color(204, 204, 204));
        casilla81.setForeground(new java.awt.Color(153, 153, 153));

        casilla82.setBackground(new java.awt.Color(204, 204, 204));
        casilla82.setForeground(new java.awt.Color(153, 153, 153));

        casilla83.setBackground(new java.awt.Color(204, 204, 204));
        casilla83.setForeground(new java.awt.Color(153, 153, 153));

        casilla84.setBackground(new java.awt.Color(204, 204, 204));
        casilla84.setForeground(new java.awt.Color(153, 153, 153));

        casilla85.setBackground(new java.awt.Color(204, 204, 204));
        casilla85.setForeground(new java.awt.Color(153, 153, 153));

        casilla86.setBackground(new java.awt.Color(204, 204, 204));
        casilla86.setForeground(new java.awt.Color(153, 153, 153));

        casilla87.setBackground(new java.awt.Color(204, 204, 204));
        casilla87.setForeground(new java.awt.Color(153, 153, 153));

        casilla88.setBackground(new java.awt.Color(204, 204, 204));
        casilla88.setForeground(new java.awt.Color(153, 153, 153));

        casilla89.setBackground(new java.awt.Color(204, 204, 204));
        casilla89.setForeground(new java.awt.Color(153, 153, 153));

        casilla90.setBackground(new java.awt.Color(204, 204, 204));
        casilla90.setForeground(new java.awt.Color(153, 153, 153));

        casilla91.setBackground(new java.awt.Color(204, 204, 204));
        casilla91.setForeground(new java.awt.Color(153, 153, 153));

        casilla92.setBackground(new java.awt.Color(204, 204, 204));
        casilla92.setForeground(new java.awt.Color(153, 153, 153));

        casilla93.setBackground(new java.awt.Color(204, 204, 204));
        casilla93.setForeground(new java.awt.Color(153, 153, 153));

        casilla94.setBackground(new java.awt.Color(204, 204, 204));
        casilla94.setForeground(new java.awt.Color(153, 153, 153));

        casilla95.setBackground(new java.awt.Color(204, 204, 204));
        casilla95.setForeground(new java.awt.Color(153, 153, 153));

        casilla96.setBackground(new java.awt.Color(204, 204, 204));
        casilla96.setForeground(new java.awt.Color(153, 153, 153));

        casilla97.setBackground(new java.awt.Color(204, 204, 204));
        casilla97.setForeground(new java.awt.Color(153, 153, 153));

        casilla98.setBackground(new java.awt.Color(204, 204, 204));
        casilla98.setForeground(new java.awt.Color(153, 153, 153));

        casilla99.setBackground(new java.awt.Color(204, 204, 204));
        casilla99.setForeground(new java.awt.Color(153, 153, 153));

        casilla100.setBackground(new java.awt.Color(204, 204, 204));
        casilla100.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla29, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla31, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla32, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla33, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla34, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla35, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla36, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla38, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla39, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla40, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla41, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla42, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla43, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla44, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla45, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla46, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla47, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla48, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla49, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla50, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla51, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla52, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla53, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla54, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla55, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla56, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla57, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla58, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla59, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla60, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla61, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla62, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla63, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla64, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla65, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla66, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla67, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla68, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla69, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla70, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla71, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla72, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla73, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla74, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla75, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla76, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla77, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla78, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla79, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla80, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla81, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla82, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla83, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla84, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla85, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla86, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla87, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla88, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla89, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla90, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(casilla91, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla92, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla93, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla94, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla95, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla96, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla97, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla98, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla99, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla100, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla100, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla99, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla98, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla97, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla96, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla95, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla94, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla93, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla92, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla91, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla90, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla89, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla88, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla87, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla86, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla85, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla84, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla83, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla82, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla81, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla80, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla79, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla78, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla77, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla76, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla75, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla74, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla73, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla72, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla71, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla70, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla69, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla68, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla67, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla66, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla65, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla64, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla63, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla62, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla61, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla60, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla59, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla58, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla57, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla56, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla55, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla54, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla53, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla52, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla51, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla50, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla49, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla48, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla47, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla46, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla45, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla44, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla43, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla42, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla41, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla40, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla39, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla38, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla36, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla35, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla34, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla33, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla32, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla31, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla29, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton casilla1;
    private javax.swing.JButton casilla10;
    private javax.swing.JButton casilla100;
    private javax.swing.JButton casilla11;
    private javax.swing.JButton casilla12;
    private javax.swing.JButton casilla13;
    private javax.swing.JButton casilla14;
    private javax.swing.JButton casilla15;
    private javax.swing.JButton casilla16;
    private javax.swing.JButton casilla17;
    private javax.swing.JButton casilla18;
    private javax.swing.JButton casilla19;
    private javax.swing.JButton casilla2;
    private javax.swing.JButton casilla20;
    private javax.swing.JButton casilla21;
    private javax.swing.JButton casilla22;
    private javax.swing.JButton casilla23;
    private javax.swing.JButton casilla24;
    private javax.swing.JButton casilla25;
    private javax.swing.JButton casilla26;
    private javax.swing.JButton casilla27;
    private javax.swing.JButton casilla28;
    private javax.swing.JButton casilla29;
    private javax.swing.JButton casilla3;
    private javax.swing.JButton casilla30;
    private javax.swing.JButton casilla31;
    private javax.swing.JButton casilla32;
    private javax.swing.JButton casilla33;
    private javax.swing.JButton casilla34;
    private javax.swing.JButton casilla35;
    private javax.swing.JButton casilla36;
    private javax.swing.JButton casilla37;
    private javax.swing.JButton casilla38;
    private javax.swing.JButton casilla39;
    private javax.swing.JButton casilla4;
    private javax.swing.JButton casilla40;
    private javax.swing.JButton casilla41;
    private javax.swing.JButton casilla42;
    private javax.swing.JButton casilla43;
    private javax.swing.JButton casilla44;
    private javax.swing.JButton casilla45;
    private javax.swing.JButton casilla46;
    private javax.swing.JButton casilla47;
    private javax.swing.JButton casilla48;
    private javax.swing.JButton casilla49;
    private javax.swing.JButton casilla5;
    private javax.swing.JButton casilla50;
    private javax.swing.JButton casilla51;
    private javax.swing.JButton casilla52;
    private javax.swing.JButton casilla53;
    private javax.swing.JButton casilla54;
    private javax.swing.JButton casilla55;
    private javax.swing.JButton casilla56;
    private javax.swing.JButton casilla57;
    private javax.swing.JButton casilla58;
    private javax.swing.JButton casilla59;
    private javax.swing.JButton casilla6;
    private javax.swing.JButton casilla60;
    private javax.swing.JButton casilla61;
    private javax.swing.JButton casilla62;
    private javax.swing.JButton casilla63;
    private javax.swing.JButton casilla64;
    private javax.swing.JButton casilla65;
    private javax.swing.JButton casilla66;
    private javax.swing.JButton casilla67;
    private javax.swing.JButton casilla68;
    private javax.swing.JButton casilla69;
    private javax.swing.JButton casilla7;
    private javax.swing.JButton casilla70;
    private javax.swing.JButton casilla71;
    private javax.swing.JButton casilla72;
    private javax.swing.JButton casilla73;
    private javax.swing.JButton casilla74;
    private javax.swing.JButton casilla75;
    private javax.swing.JButton casilla76;
    private javax.swing.JButton casilla77;
    private javax.swing.JButton casilla78;
    private javax.swing.JButton casilla79;
    private javax.swing.JButton casilla8;
    private javax.swing.JButton casilla80;
    private javax.swing.JButton casilla81;
    private javax.swing.JButton casilla82;
    private javax.swing.JButton casilla83;
    private javax.swing.JButton casilla84;
    private javax.swing.JButton casilla85;
    private javax.swing.JButton casilla86;
    private javax.swing.JButton casilla87;
    private javax.swing.JButton casilla88;
    private javax.swing.JButton casilla89;
    private javax.swing.JButton casilla9;
    private javax.swing.JButton casilla90;
    private javax.swing.JButton casilla91;
    private javax.swing.JButton casilla92;
    private javax.swing.JButton casilla93;
    private javax.swing.JButton casilla94;
    private javax.swing.JButton casilla95;
    private javax.swing.JButton casilla96;
    private javax.swing.JButton casilla97;
    private javax.swing.JButton casilla98;
    private javax.swing.JButton casilla99;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
